### ISSUE TITLE
improve error handling

### ISSUE THREAD

**Issue by dna909** [dna909/ioBroker.homeconnect#14]

**Comment by dna909** [comment]
BAD GATEWAY:


2019-05-23 07:38:41.815  - [31merror[39m: homeconnect.0 undefined
2019-05-23 07:38:42.575  - [31merror[39m: homeconnect.0 undefined
2019-05-23 07:38:52.283  - [31merror[39m: homeconnect.0 502
2019-05-23 07:38:52.283  - [31merror[39m: homeconnect.0 Error (BOSCH-HNG6764S6-68A40E07711C)
2019-05-23 07:38:52.283  - [31merror[39m: homeconnect.0 FEHLER
2019-05-23 07:38:52.286  - [31merror[39m: homeconnect.0 uncaught exception: 502
2019-05-23 07:38:52.287  - [31merror[39m: homeconnect.0 Error: 502
    at EventSource.eventSource.onerror.err (/opt/iobroker/node_modules/iobroker.homeconnect/main.js:274:27)
    at emitOne (events.js:116:13)
    at EventSource.emit (events.js:211:7)
    at _emit (/opt/iobroker/node_modules/eventsource/lib/eventsource.js:242:17)
    at ClientRequest.<anonymous> (/opt/iobroker/node_modules/eventsource/lib/eventsource.js:136:9)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:558:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
