### ISSUE TITLE
configuration

### ISSUE THREAD

**Issue by firelook** [dna909/ioBroker.homeconnect#3]
I have some troubled with my dish washer:
this is the log : 
`

host.Obelix | 2018-11-28 09:59:17.904 | error | instance system.adapter.homeconnect.0 terminated with code 0 (OK)
-- | -- | -- | --
host.Obelix | 2018-11-28 09:59:17.904 | error | Caught by controller[0]: at processImmediate [as _immediateCallback] (timers.js:617:5)
host.Obelix | 2018-11-28 09:59:17.904 | error | Caught by controller[0]: at tryOnImmediate (timers.js:645:5)
host.Obelix | 2018-11-28 09:59:17.904 | error | Caught by controller[0]: at Immediate.<anonymous> (C:\iobroker\node_modules\iobroker.js-controller\lib\adapter.js:3429:38)
host.Obelix | 2018-11-28 09:59:17.904 | error | Caught by controller[0]: at Adapter.emit (events.js:191:7)
host.Obelix | 2018-11-28 09:59:17.904 | error | Caught by controller[0]: at emitTwo (events.js:106:13)
host.Obelix | 2018-11-28 09:59:17.904 | error | Caught by controller[0]: at Adapter.<anonymous> (C:\iobroker\node_modules\iobroker.homeconnect\main.js:363:9)
host.Obelix | 2018-11-28 09:59:17.904 | error | Caught by controller[0]: at inventory (C:\iobroker\node_modules\iobroker.homeconnect\main.js:367:13)
host.Obelix | 2018-11-28 09:59:17.904 | error | Caught by controller[0]: at inventorySub (C:\iobroker\node_modules\iobroker.homeconnect\main.js:522:5)
host.Obelix | 2018-11-28 09:59:17.904 | error | Caught by controller[0]: at devicesDp (C:\iobroker\node_modules\iobroker.homeconnect\main.js:556:42)
host.Obelix | 2018-11-28 09:59:17.904 | error | Caught by controller[0]: TypeError: Cannot read property 'length' of undefined

`

**Comment by firelook** [comment]
![image](https://user-images.githubusercontent.com/3873193/49140411-86a98a00-f2f4-11e8-8cf0-25127cc3f26d.png)

**Comment by firelook** [comment]
![image](https://user-images.githubusercontent.com/3873193/49140469-9fb23b00-f2f4-11e8-8c66-2fb449bad9a1.png)
