### ISSUE TITLE
TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by vr6syncro** [dna909/ioBroker.homeconnect#43]
`

homeconnect.0 | 2020-06-05 20:52:43.404 | info | (7399) BOSCH-PXY675DW4E-XY: There is no program active
-- | -- | -- | --
homeconnect.0 | 2020-06-05 20:52:41.912 | error | (7399) {"data":{"programs":[]}}
homeconnect.0 | 2020-06-05 20:52:41.911 | error | (7399) /programs
homeconnect.0 | 2020-06-05 20:52:41.911 | error | (7399) TypeError: Cannot read property 'forEach' of undefined at /opt/iobroker/node_modules/iobroker.homeconnect/main.js:929:57 at Array.forEach (<anonymous>) at /opt/iobroker/node_modules
homeconnect.0 | 2020-06-05 20:52:41.906 | error | (7399) TypeError: Cannot read property 'forEach' of undefined
homeconnect.0 | 2020-06-05 20:52:41.906 | debug | (7399) {"data":{"programs":[]}}
homeconnect.0 | 2020-06-05 20:52:41.905 | debug | (7399) /programs
homeconnect.0 | 2020-06-05 20:52:40.409 | debug | (7399) Create State: BOSCH-PXY675DW4E-XY.settings.BSH_Common_Setting_PowerState
homeconnect.0 | 2020-06-05 20:52:40.409 | debug | (7399) Rate per min: 26
homeconnect.0 | 2020-06-05 20:52:40.408 | debug | (7399) {"data":{"settings":[{"key":"BSH.Common.Setting.PowerState","value":"BSH.Common.EnumType.PowerState.Off","name":"Energiezustand","displayvalue":"Aus"}]}}
homeconnect.0 | 2020-06-05 20:52:40.408 | debug | (7399) /settings
homeconnect.0 | 2020-06-05 20:52:38.907 | debug | (7399) Create State: BOSCH-PXY675DW4E-XY.status.BSH_Common_Status_RemoteControlActive
homeconnect.0 | 2020-06-05 20:52:38.907 | debug | (7399) Create State: BOSCH-PXY675DW4E-XY.status.BSH_Common_Status_OperationState
homeconnect.0 | 2020-06-05 20:52:38.906 | debug | (7399) Create State: BOSCH-PXY675DW4E-XY.status.BSH_Common_Status_LocalControlActive
homeconnect.0 | 2020-06-05 20:52:38.905 | debug | (7399) {"data":{"status":[{"key":"BSH.Common.Status.LocalControlActive","value":false,"name":"Lokale Bedienung aktiv"},{"key":"BSH.Common.Status.OperationState","value":"BSH.Common.EnumType.OperationS
homeconnect.0 | 2020-06-05 20:52:38.905 | debug | (7399) /status

`

**Comment by TA2k** [comment]
versio 0.0.30 is installed?

**Comment by vr6syncro** [comment]
Installierte Version:0.0.30
Yes

**Comment by th4git** [comment]
Same error for me: since v0.30 - probably related to my washing machine "BOSCH-WAYH2891" - the message

2020-07-18 12:56:39.077 - error: homeconnect.0 (21203) TypeError: Cannot read property 'forEach' of undefined
2020-07-18 12:56:39.078 - error: homeconnect.0 (21203) TypeError: Cannot read property 'forEach' of undefined
at rootItems.forEach (/opt/iobroker/node_modules/iobroker.homeconnect/main.js:929:57)
at Array.forEach ()
at sendRequest.then (/opt/iobroker/node_modules/iobroker.homeconnect/main.js:920:39)
at process._tickCallback (internal/process/next_tick.js:68:7)
2020-07-18 12:56:39.078 - error: homeconnect.0 (21203) /programs
2020-07-18 12:56:39.078 - error: homeconnect.0 (21203) {"data":{"programs":[]}}

comes at the start of the HomeConnect adapter.
For both other devices (cooktop+ oven) I receive the correct message "There is no program active / selected" directly before the above error.

Using version 0.26 everything worked like a charm. I appreciate your good work! So it would be very kind to have this fixed - thanks in advance!
