### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Guenda85** [dna909/ioBroker.homeconnect#6]
Siemens SN478S36TE; configured according manual

2018-12-08 10:21:52.436 - error: homeconnect.0 Bitte ioBroker authorisieren!! =====>>> https://verify.home-connect.com?user_code=JTFG-ZX2W
--
2018-12-08 10:22:02.530 - info: homeconnect.0 Accestoken generiert!
2018-12-08 10:22:02.693 - error: homeconnect.0 uncaught exception: Cannot read property 'length' of undefined
2018-12-08 10:22:02.699 - error: Caught by controller[0]: (node:18102) UnhandledPromiseRejectionWarning: ReferenceError: getTokenRefreshInterval is not defined
2018-12-08 10:22:02.699 - error: Caught by controller[0]: at auth.tokenGet.then (/opt/iobroker/node_modules/iobroker.homeconnect/main.js:192:40)
2018-12-08 10:22:02.699 - error: Caught by controller[0]: at
2018-12-08 10:22:02.699 - error: Caught by controller[0]: at process._tickCallback (internal/process/next_tick.js:189:7)
2018-12-08 10:22:02.699 - error: Caught by controller[1]: (node:18102) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
2018-12-08 10:22:02.699 - error: Caught by controller[2]: (node:18102) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2018-12-08 10:22:02.699 - error: Caught by controller[3]: TypeError: Cannot read property 'length' of undefined
2018-12-08 10:22:02.699 - error: Caught by controller[3]: at devicesDp (/opt/iobroker/node_modules/iobroker.homeconnect/main.js:621:43)
2018-12-08 10:22:02.699 - error: Caught by controller[3]: at inventorySub (/opt/iobroker/node_modules/iobroker.homeconnect/main.js:587:5)
2018-12-08 10:22:02.699 - error: Caught by controller[3]: at inventory (/opt/iobroker/node_modules/iobroker.homeconnect/main.js:432:13)
2018-12-08 10:22:02.699 - error: Caught by controller[3]: at Adapter. (/opt/iobroker/node_modules/iobroker.homeconnect/main.js:428:9)
2018-12-08 10:22:02.699 - error: Caught by controller[3]: at emitTwo (events.js:126:13)
2018-12-08 10:22:02.699 - error: Caught by controller[3]: at Adapter.emit (events.js:214:7)
2018-12-08 10:22:02.699 - error: Caught by controller[3]: at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3429:38)
2018-12-08 10:22:02.699 - error: Caught by controller[3]: at runCallback (timers.js:810:20)
2018-12-08 10:22:02.700 - error: Caught by controller[3]: at tryOnImmediate (timers.js:768:5)
2018-12-08 10:22:02.700 - error: Caught by controller[3]: at processImmediate [as _immediateCallback] (timers.js:745:5)
2018-12-08 10:22:02.700 - error: host.gke-sv-web instance system.adapter.homeconnect.0 terminated with code 0 (OK)

**Comment by vr6syncro** [comment]
Bosch PXY675DW4E
`

host.ioBroker | 2018-12-15 16:35:14.967 | error | instance system.adapter.homeconnect.0 terminated with code 0 (OK)
-- | -- | -- | --
Caught | 2018-12-15 16:35:14.967 | error | by controller[0]: at processImmediate [as _immediateCallback] (timers.js:617:5)
Caught | 2018-12-15 16:35:14.967 | error | by controller[0]: at tryOnImmediate (timers.js:645:5)
Caught | 2018-12-15 16:35:14.967 | error | by controller[0]: at runCallback (timers.js:672:20)
Caught | 2018-12-15 16:35:14.967 | error | by controller[0]: at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3725:38)
Caught | 2018-12-15 16:35:14.967 | error | by controller[0]: at Adapter.emit (events.js:191:7)
Caught | 2018-12-15 16:35:14.966 | error | by controller[0]: at emitTwo (events.js:106:13)
Caught | 2018-12-15 16:35:14.966 | error | by controller[0]: at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.homeconnect/main.js:428:9)
Caught | 2018-12-15 16:35:14.966 | error | by controller[0]: at inventory (/opt/iobroker/node_modules/iobroker.homeconnect/main.js:432:13)
Caught | 2018-12-15 16:35:14.966 | error | by controller[0]: at inventorySub (/opt/iobroker/node_modules/iobroker.homeconnect/main.js:603:5)
Caught | 2018-12-15 16:35:14.966 | error | by controller[0]: at devicesDp (/opt/iobroker/node_modules/iobroker.homeconnect/main.js:621:42)
Caught | 2018-12-15 16:35:14.966 | error | by controller[0]: TypeError: Cannot read property 'length' of undefined
homeconnect.0 | 2018-12-15 16:35:14.955 | info | terminating
homeconnect.0 | 2018-12-15 16:35:14.952 | info | cleaned everything up...
homeconnect.0 | 2018-12-15 16:35:14.952 | error | at processImmediate [as _immediateCallback] (timers.js:617:5)
homeconnect.0 | 2018-12-15 16:35:14.952 | error | at tryOnImmediate (timers.js:645:5)
homeconnect.0 | 2018-12-15 16:35:14.952 | error | at runCallback (timers.js:672:20)
homeconnect.0 | 2018-12-15 16:35:14.952 | error | at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3725:38)
homeconnect.0 | 2018-12-15 16:35:14.952 | error | at Adapter.emit (events.js:191:7)
homeconnect.0 | 2018-12-15 16:35:14.952 | error | at emitTwo (events.js:106:13)
homeconnect.0 | 2018-12-15 16:35:14.952 | error | at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.homeconnect/main.js:428:9)
homeconnect.0 | 2018-12-15 16:35:14.952 | error | at inventory (/opt/iobroker/node_modules/iobroker.homeconnect/main.js:432:13)
homeconnect.0 | 2018-12-15 16:35:14.952 | error | at inventorySub (/opt/iobroker/node_modules/iobroker.homeconnect/main.js:603:5)
homeconnect.0 | 2018-12-15 16:35:14.952 | error | at devicesDp (/opt/iobroker/node_modules/iobroker.homeconnect/main.js:621:42)
homeconnect.0 | 2018-12-15 16:35:14.952 | error | TypeError: Cannot read property 'length' of undefined
homeconnect.0 | 2018-12-15 16:35:14.952 | error | uncaught exception: Cannot read property 'length' of undefined
homeconnect.0 | 2018-12-15 16:35:14.752 | info | starting. Version 0.0.5 in /opt/iobroker/node_modules/iobroker.homeconnect, node: v6.14.4

`

**Comment by Guenda85** [comment]
welchen JSON? den vom "homeconnect.0.dev.homeappliancesJSON" Objekt? ist der hier:

{"data":{"homeappliances":[{"name":"Geschirrspüler","brand":"Siemens","vib":"SN478S36TE","connected":true,"type":"Dishwasher","enumber":"SN478S36TE/53","haId":"SIEMENS-SN478S36TE-68A40E239B0B"}]}}

da wäre als Type "Dishwasher" enthalten!? oder was entnehme ich deinem Verweis auf main.js:602? in den case dürfte er nicht laufen!?

**Comment by vr6syncro** [comment]
`

homeconnect.0 | 2018-12-21 13:53:30.900 | info | terminating
-- | -- | -- | --
homeconnect.0 | 2018-12-21 13:53:30.897 | info | cleaned everything up...
homeconnect.0 | 2018-12-21 13:53:30.897 | error | at processImmediate [as _immediateCallback] (timers.js:617:5)
homeconnect.0 | 2018-12-21 13:53:30.897 | error | at tryOnImmediate (timers.js:645:5)
homeconnect.0 | 2018-12-21 13:53:30.897 | error | at runCallback (timers.js:672:20)
homeconnect.0 | 2018-12-21 13:53:30.897 | error | at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3725:38)
homeconnect.0 | 2018-12-21 13:53:30.897 | error | at Adapter.emit (events.js:191:7)
homeconnect.0 | 2018-12-21 13:53:30.897 | error | at emitTwo (events.js:106:13)
homeconnect.0 | 2018-12-21 13:53:30.897 | error | at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.homeconnect/main.js:431:9)
homeconnect.0 | 2018-12-21 13:53:30.897 | error | at inventory (/opt/iobroker/node_modules/iobroker.homeconnect/main.js:435:13)
homeconnect.0 | 2018-12-21 13:53:30.897 | error | at inventorySub (/opt/iobroker/node_modules/iobroker.homeconnect/main.js:612:5)
homeconnect.0 | 2018-12-21 13:53:30.897 | error | at devicesDp (/opt/iobroker/node_modules/iobroker.homeconnect/main.js:632:42)
homeconnect.0 | 2018-12-21 13:53:30.897 | error | TypeError: Cannot read property 'length' of undefined
homeconnect.0 | 2018-12-21 13:53:30.897 | error | uncaught exception: Cannot read property 'length' of undefined
homeconnect.0 | 2018-12-21 13:53:30.891 | debug | Type= Hob
homeconnect.0 | 2018-12-21 13:53:30.666 | info | starting. Version 0.0.5 in /opt/iobroker/node_modules/iobroker.homeconnect, node: v6.14.4

`

Das Problem ist der Json vom Hob (Herdplatte/Kochfeld) ich weiß das Homeconnect da noch dran arbeitet.

**Comment by Guenda85** [comment]
Hi,

eben gemacht – anbei das neue Log:
2018-12-21 15:47:47.603 - debug: homeconnect.0 objectDB connected

2018-12-21 15:47:47.615 - debug: homeconnect.0 statesDB connected

2018-12-21 15:47:47.720 - info: homeconnect.0 starting. Version 0.0.5 in /opt/iobroker/node_modules/iobroker.homeconnect, node: v8.14.0

2018-12-21 15:47:47.880 - debug: homeconnect.0 Type= Dishwasher

2018-12-21 15:47:47.888 - error: Caught by controller[0]: TypeError: Cannot read property 'length' of undefined

2018-12-21 15:47:47.888 - error: Caught by controller[0]: at devicesDp (/opt/iobroker/node_modules/iobroker.homeconnect/main.js:632:43)

2018-12-21 15:47:47.888 - error: Caught by controller[0]: at inventorySub (/opt/iobroker/node_modules/iobroker.homeconnect/main.js:592:5)

2018-12-21 15:47:47.888 - error: Caught by controller[0]: at inventory (/opt/iobroker/node_modules/iobroker.homeconnect/main.js:435:13)

2018-12-21 15:47:47.888 - error: Caught by controller[0]: at Adapter. (/opt/iobroker/node_modules/iobroker.homeconnect/main.js:431:9)

2018-12-21 15:47:47.888 - error: Caught by controller[0]: at emitTwo (events.js:126:13)

2018-12-21 15:47:47.888 - error: Caught by controller[0]: at Adapter.emit (events.js:214:7)

2018-12-21 15:47:47.888 - error: Caught by controller[0]: at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3429:38)

2018-12-21 15:47:47.888 - error: Caught by controller[0]: at runCallback (timers.js:810:20)

2018-12-21 15:47:47.888 - error: Caught by controller[0]: at tryOnImmediate (timers.js:768:5)

2018-12-21 15:47:47.888 - error: Caught by controller[0]: at processImmediate [as _immediateCallback] (timers.js:745:5)

2018-12-21 15:47:47.888 - error: host.gke-sv-web instance system.adapter.homeconnect.0 terminated with code 0 (OK)

2018-12-21 15:47:47.888 - info: host.gke-sv-web Restart adapter system.adapter.homeconnect.0 because enabled


Viele Grüße,
Günter

Von: dna909 <notifications@github.com>
Gesendet: Freitag, 21. Dezember 2018 09:23
An: dna909/ioBroker.homeconnect <ioBroker.homeconnect@noreply.github.com>
Cc: Guenter Keilhammer <guenter@keilhammer.com>; Author <author@noreply.github.com>
Betreff: Re: [dna909/ioBroker.homeconnect] Cannot read property 'length' of undefined (#6)


welchen JSON? den vom "homeconnect.0.dev.homeappliancesJSON" Objekt? ist der hier:

{"data":{"homeappliances":[{"name":"Geschirrspüler","brand":"Siemens","vib":"SN478S36TE","connected":true,"type":"Dishwasher","enumber":"SN478S36TE/53","haId":"SIEMENS-SN478S36TE-68A40E239B0B"}]}}

da wäre als Type "Dishwasher" enthalten!? oder was entnehme ich deinem Verweis auf main.js:602? in den case dürfte er nicht laufen!?

Installiere mal bitte noch mal neu und stell den Adapter mal auf Debug. Habe grad noch etwas Logging hinzugefügt. Mal schauen, ob ich da dann das Problem sehe.

**Comment by TJJochen** [comment]
Hallo bekomme es auch nicht zum Laufen...
Habe einen SIEMENS Kaffeevollautomat EQ.9 connect s900 TI909701HC versucht über den HomeConnect Adfapter in ioBroker zu integrieren.

Nachdem ich aber die Freigabe erteile und den API Token generiere schreibt der Adapter mir das Log voll und startet immer wieder neu.


host.IOBroker-Master | 2018-12-27 12:32:31.581 | error | instance system.adapter.homeconnect.0 terminated with code 0 (OK)
-- | -- | -- | --
host.IOBroker-Master | 2018-12-27 12:32:31.581 | error | Caught by controller[1]: at processImmediate (timers.js:647:5)
host.IOBroker-Master | 2018-12-27 12:32:31.581 | error | Caught by controller[1]: at tryOnImmediate (timers.js:665:5)
host.IOBroker-Master | 2018-12-27 12:32:31.581 | error | Caught by controller[1]: at runCallback (timers.js:694:18)
host.IOBroker-Master | 2018-12-27 12:32:31.581 | error | Caught by controller[1]: at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3429:38)
host.IOBroker-Master | 2018-12-27 12:32:31.581 | error | Caught by controller[1]: at Adapter.emit (events.js:182:13)
host.IOBroker-Master | 2018-12-27 12:32:31.581 | error | Caught by controller[1]: at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.homeconnect/main.js:431:9)
host.IOBroker-Master | 2018-12-27 12:32:31.581 | error | Caught by controller[1]: at inventory (/opt/iobroker/node_modules/iobroker.homeconnect/main.js:435:13)
host.IOBroker-Master | 2018-12-27 12:32:31.581 | error | Caught by controller[1]: at inventorySub (/opt/iobroker/node_modules/iobroker.homeconnect/main.js:622:5)
host.IOBroker-Master | 2018-12-27 12:32:31.581 | error | Caught by controller[1]: at devicesDp (/opt/iobroker/node_modules/iobroker.homeconnect/main.js:632:43)
host.IOBroker-Master | 2018-12-27 12:32:31.581 | error | Caught by controller[1]: TypeError: Cannot read property 'length' of undefined
host.IOBroker-Master | 2018-12-27 12:32:31.580 | error | Caught by controller[0]: (node:8622) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js proces
host.IOBroker-Master | 2018-12-27 12:32:31.580 | error | Caught by controller[0]: (node:8622) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by re
host.IOBroker-Master | 2018-12-27 12:32:31.580 | error | Caught by controller[0]: at process._tickCallback (internal/process/next_tick.js:68:7)
host.IOBroker-Master | 2018-12-27 12:32:31.580 | error | Caught by controller[0]: at auth.tokenGet.then (/opt/iobroker/node_modules/iobroker.homeconnect/main.js:195:40)
host.IOBroker-Master | 2018-12-27 12:32:31.579 | error | Caught by controller[0]: (node:8622) UnhandledPromiseRejectionWarning: ReferenceError: getTokenRefreshInterval is not defined
homeconnect.0 | 2018-12-27 12:32:31.342 | info | Accestoken generiert!

Plattform: linux
Die Architektur: x64
CPUs: 2
Geschwindigkeit: 3292 MHz
Modell: Intel Core i7 (Nehalem Class Core i7)
RAM: 1.9 GB
System uptime: 15 T. 12:58:15
Node.js: v10.10.0
Adapter zählen: 238
NPM: v6.4.1
Uptime: 00:14:04


Weiß jemand Rat, wo ich bei der Fehlersuche anfangen kann?

Schöne Grüße
Jochen

**Comment by tFaster** [comment]
Der Fehler liegt im JSON.parse in Zeile 153 in Datei main.js.
Parse liefert hier nur das "Oven" Objekt zurück.
Für was ist das JSON.stringify und dann JSON.parse gut? wieso nicht gleich die richtige Objectstruktur in deviceArray schreiben und gut ist?

**Comment by Guenda85** [comment]
v0.0.6 funktioniert -> der Objekt-Baum wurde erfolgreich aufgebaut und einige Objekte werden auch korrekt gefüllt. Kein Fehler im Log -> zumindest bei meiner Spülmaschine :-D
